### ISSUE TITLE
How to realize the training data and CART (Classification And Regression Trees ) in the paper？

### ISSUE THREAD

**Issue by Jackjiayou** [alibaba/clusterdata#128] opened 2022-03-10 14:44 UTC
![image](https://user-images.githubusercontent.com/43378246/157676823-2505fd74-1976-4a9c-b916-29feebfe4965.png)
![image](https://user-images.githubusercontent.com/43378246/157676909-dd2ee5a2-96f5-4b7b-974d-3f5a6f5a04a6.png)
 I want to realize the prediction method in this paper. I used the pai_task_table，pai_job_table, 
pai_group_tag_table to create the data as below.  With Cart Regression Trees of  Sklearn to fit the data. The result is not good. I think I must be doing something wrong.
![image](https://user-images.githubusercontent.com/43378246/157680433-51330bf3-95c8-4f6f-ae50-0c249ee85bf1.png)
![image](https://user-images.githubusercontent.com/43378246/157680692-a48b96c5-ccf9-4241-b11d-2743626b54a5.png)
![image](https://user-images.githubusercontent.com/43378246/157684736-18f45caf-eb56-4a0d-9207-0d707fc5d656.png)
I am looking forward your reply. Thanks.

**Comment by qzweng** [comment] 2023-11-15 23:32
I would suggest reproducing the CART estimation with the following details:

1. Filter out tasks that recur fewer than 5 times, as suggested in the paper.
2. Group the tasks by the "group" feature and then apply CART using the remaining features such as "plan_cpu", "plan_gpu", "user", etc.

The reason for grouping the tasks by the "Group" feature is that it is a compound feature that originally consisted of multiple confidential entries, such as entry scripts, command-line parameters, data sources, and sinks. These entries are not allowed to be released, so the "Group" tag is released as salted MD5 strings. However, this can potentially affect the performance of CART.

Thanks to the trials and feedback from the community, it has become clear that the "Group" tag plays an important role that cannot be adequately captured through naive embedding methods. Therefore, we have developed the above steps, which should help reproduce the estimation with fairly accurate results. Thank you.

**Closed by qzweng** 2023-11-15 23:32 UTC
