### ISSUE TITLE
Lifecycle of Batch Task

### ISSUE THREAD

**Issue by jcarreira** [alibaba/clusterdata#27] opened 2018-02-26 20:50 UTC
In the task table (batch_task.csv) each task can have different status: _(Ready | Waiting | Running | Terminated | Failed | Cancelled)_.

With some analysis it seems that each pair job-id/task-id only appears once in batch_task.csv.

Shouldn't tasks go through different stages, for instance, Waiting->Ready->Running->Terminated, and thus appear multiple times in this file?

What do the _create_timestamp_ and _modify_timestamp_ mean for an entry with Running status vs one with Terminated status? Do tasks that have 'Running' status ever finish? If they do, when does that happen?

**Comment by lioncruise** [comment] 2018-02-27 03:44
I think in this version of the dataset, `batch_task` table only records latest state information of the task, and there will be a next version of data soon which might include task;s DAG dependencies and task state lifecycle as you mentioned. 

As for the question about **Running** and **Terminated** status, if the data collecting is not based on event model, I think **Running** means for the task has started to execute but till the **modify_timestamp** it has not finished while **Terminated** means for the task has finished till the **modify_timestamp**. I guess it might be caused by two kind of situation: 1. the task indeed have not finished so the monitor just collect **Running** status as the latest status; 2. the **Terminating** status lost during data collecting. 

In the version of data,  there are 3567 **Running** status task and 67013 **Terminated** status task, **Running** task is a minority. I think we can ignore this and just wait the next version of data.

**Comment by HaiyangDING** [comment] 2018-03-02 06:15
@jcarreira thanks for posting your question here.

@lioncruise has already said what I would say should I answer the question, thanks and sorry for my delayed response here.

**Comment by HaiyangDING** [comment] 2018-12-20 07:59
Closing the issue.

**Closed by HaiyangDING** 2018-12-20 07:59 UTC
