### ISSUE TITLE
Repeated entries in container_event.csv and resources requests above machine capacity

### ISSUE THREAD

**Issue by jcarreira** [alibaba/clusterdata#33] opened 2018-03-07 04:31 UTC
In the file _container_event.csv_ I find that 1) some online instances seem to be created twice in the same timestamp/machine and 2) values of _plan_mem_ can be higher than the machine's capacity.

For instance, in the file _container_event.csv I_ find the following consecutive lines:

> 0,Create,10772,85,4,0.042409339165997983,0.0340851218221338,32|33|34|35,
0,Create,10772,85,4,**0.9999633571040303**,0.0340851218221338,32|33|34|35,

The lines are the same, except the _plan_mem_ value. Also when looking into the capacity for machine #85 in file _server_event.csv_ I see:

> 0,85,add,,64,**0.6899697150104833,1**

It seems that this machine doesn't have enough memory for the creation of the service (0.68 < 0.99).

My questions are:
1. Can a service be created twice (like the example above)?
2. Is this request for 0.99 of memory valid considering that the machine only has 0.68?
 
Can you please explain this?

Thank you in advance for the clarifications.

**Comment by lioncruise** [comment] 2018-03-07 06:48
I found this problem a month ago: [https://github.com/lioncruise/alibaba-clusterdata-analysis/issues/1](https://github.com/lioncruise/alibaba-clusterdata-analysis/issues/1). I think it's caused by data collecting error probably, just ignore the second duplicate record requested 0.99 memory.

**Comment by HaiyangDING** [comment] 2018-03-08 09:54
@jcarreira 

Sorry for the delay in response. I agree with what @lioncruise mentioned above.

Thank both of you on the interest and effort on the data.

**Comment by HaiyangDING** [comment] 2018-12-20 07:50
Closing the issue.

**Closed by HaiyangDING** 2018-12-20 07:50 UTC
