### ISSUE TITLE
Data Inconsistency in container_event and container_usage

### ISSUE THREAD

**Issue by gaocegege** [alibaba/clusterdata#13] opened 2017-11-17 09:14 UTC
Hi, I tried to analyse the data about long-running jobs in alibaba trace. But I found that there are some records in container_usage.csv that the instance_id of the record does not exists in container_event.csv.

For instance, there is an entry in container_usage.csv:

```
['44700', '9088', '9.199999999999992', '35.70000076289956', '5.659999847414268', '0.3200000047682117', '0.3600000083444044', '0.4000000059600084', '0.2258861563823704', '0.2572154391695187', '2.60268044472', '2.83470249176']
```

The instance_id is 9088 but there is no entry in container_event.csv which instance_id is 9088.

There are 1480906 entries in container_usage.csv totally, and 24570 of them are missed in container_event.csv. What does it mean?

I'd appreciate it if you could help me. @furykerry 

Best,
Ce Gao

**Comment by CoffeeCandy** [comment] 2017-11-19 03:36
i found this problem too  T T

**Comment by allencloud** [comment] 2017-11-19 10:35
Thanks for your feedback. We will take a look and give feedback as soon as possible.
@furykerry

**Comment by HaiyangDING** [comment] 2017-12-29 02:33
Hi,  @gaocegege @CoffeeCandy,

First, sorry about the delay in answering your questions.

There are indeed missing entries in the data set as you mentioned, and I think it is likely to be caused by some errors in collecting/cleaning the data. We are sorry about this and we will add this as "Known Issues" in our WIKI.

As for this error, I would suggest filtering out the flaw data in the analysis in which missing data is critical. We are now collecting suggestions for the data set and will publish another version in near future to fulfill the requirements from the community and collaborators.

Thank you for your interest in our data and we look forward to hearing more from you.

**Comment by gaocegege** [comment] 2017-12-29 03:08
@HaiyangDING 

Thanks for your reply and I will keep an eye on this repo. And could you give us a timeline about the new release? Or could we file a issue to keep track of the new release then we could watch this issue and know when to have a try on it.

**Comment by HaiyangDING** [comment] 2017-12-29 04:29
@gaocegege 

Sure, feel free to file an issue here and we could also collect suggestions for new version of data. Currently, we have a DAG data planned to be release soon.

**Comment by HaiyangDING** [comment] 2018-01-10 11:37
Closing the issue. I will open an issue to collect suggestion about the next version of data to be released.

**Comment by HaiyangDING** [comment] 2018-01-10 11:37
Closing the issue. I will open an issue to collect suggestion about the next version of data to be released.

**Closed by HaiyangDING** 2018-01-10 11:37 UTC
