### ISSUE TITLE
question about the time of trace

### ISSUE THREAD

**Issue by CoffeeCandy** [alibaba/clusterdata#12] opened 2017-11-13 09:12 UTC
I test the trace finding that  the time in server usage csv is from 39600 to 82500,almost 11 hours,But the README says there are 24 hours,then i test the batch_instance,the time is also 39600 to 82500,may i ask  was i testing  wrong?

**Comment by gaocegege** [comment] 2017-11-13 13:53
> We’ll first open a data of 1000 server over 12 hours

The text in the wiki is 12 hours, then I think it might be a typo.

@allencloud

**Comment by CoffeeCandy** [comment] 2017-11-14 06:41
thankyou,please do not mind  i want to  ask another question,i test the batch_instance.csv,i found that ready status  only appear at timestamp of 0,does it means you only commit all  the batch jobs at 0 and only once?

**Comment by CoffeeCandy** [comment] 2017-11-14 11:42
i check the trace_201708,it said a time of 0 represents the event occur before the trace period. ,but i feel confused that why the timestamp of server_usage begin from 39600?and it ends at 82500,it seems almost 12 hours, it looks like right that  your timestamp begin from 39600, but the timestamp of server_event begin at 0 .the timestamp of container_event also begin from 0,but after that it skip to 34424?

**Comment by CoffeeCandy** [comment] 2017-11-14 13:01
please do not be mad at me,it looks like i have many problem.i test container_event,i find 
![image](https://user-images.githubusercontent.com/11613801/32781041-7b6839de-c97e-11e7-8706-838cf43a25c2.png),i do not understand why they have same  timestamp ,same instance_id and same machine_id,i don't know what it means

**Comment by CoffeeCandy** [comment] 2017-11-19 03:23
hey,i find another problem,the trace_201707.md said that  for instance in running and failed status, start time is non-zero but end time is zero.
![al1png](https://user-images.githubusercontent.com/11613801/32987094-f54c030c-cd1b-11e7-88d4-69ac0abbbb12.png)
which end time is not zero,can i change these end time to zero by myself?
,

**Comment by CoffeeCandy** [comment] 2017-11-19 03:34
can i treate the Terminated as finish successfully?and i found there are so much missing datas in batch_instance.csv,they are  real_mem_max and real_mem_avg in Terminated status in batch_instance.csv

**Comment by furykerry** [comment] 2017-11-20 13:09
> I test the trace finding that the time in server usage csv is from 39600 to 82500,almost 11 hours,But the README says there are 24 hours,

we disclose instances and machine usages data only for 12 consecutive hours. Not a typo

**Comment by CoffeeCandy** [comment] 2017-11-26 03:01
may i ask does the 7th  field number of cpus requested per instance in the task in batch_task  means that every instance of the task request or total instance of a task request

**Comment by CoffeeCandy** [comment] 2017-11-30 01:58
may i ask does all the instance both batch and container instance run in container instead of vm

**Comment by allencloud** [comment] 2017-11-30 02:46
I would like to invite @furykerry again to reply to your question. 🍻

**Comment by HaiyangDING** [comment] 2017-12-29 04:18
@CoffeeCandy 
> may i ask does the 7th field number of cpus requested per instance in the task in batch_task means that every instance of the task request or total instance of a task request

Every instance of the task needs that amount of cpu

> i found some of cpus requested per instance in the task in batch_task less than the same of job and task 's 11th field maximum normalized memory of actual instance running in batch_instance

IIUC, your question is about why some value at 11th of batch_instance.csv is (sometimes) larger than the corresponding record in batch_task.csv, right? The 11th of batch_instance.csv is a normalized value against its request, so these two variables should not be compared numerically.

> may i ask does all the instance both batch and container instance run in container instead of vm

Container instances are definitely running in Alibaba's internal containers (aka Pouch, and we have had [Pouch](https://github.com/alibaba/pouch) opensourced.)

> can i treate the Terminated as finish successfully?and i found there are so much missing datas in batch_instance.csv,they are real_mem_max and real_mem_avg in Terminated status in batch_instance.csv

You are right, and we will add this as a known issue in our WIKI and fix them in the next version of data.

> please do not be mad at me,it looks like i have many problem.i test container_event,i find
image,i do not understand why they have same timestamp ,same instance_id and same machine_id,i don't know what it means

I think it is a flaw in the collecting / cleaning data. You may need to do filtering / replacing / alignment according to our description of the data. We will try to eliminate such confusion in the next version.

At last, thank you very much for your interest and suggestions on our data.

**Comment by CoffeeCandy** [comment] 2018-01-01 05:29
@HaiyangDING thanks for your reply,and i do not fully understand what your means in The 11th of batch_instance.csv is a normalized value against its request,is that means the cpu filed in batch_instance.csv is the percent used of request?

**Comment by CoffeeCandy** [comment] 2018-01-01 05:43
@HaiyangDING thanks for your reply and happy new year! I do not fully understand what your means of he 11th of batch_instance.csv is a normalized value against its request,if it is normalized value against its request,why there are many values more than 1,or do i have misunderstand of normalized ?

**Comment by CoffeeCandy** [comment] 2018-01-04 12:17
as the schema.csv said the usage is record every 1 minutes,and average over 300 seconds. were the fields linux cpu load average of 1 minute , linux cpu load average of 5 minute  ,linux cpu load average of 15 minute  in server_usage.csv  computed in same way too?

**Comment by HaiyangDING** [comment] 2018-01-07 03:04
> @HaiyangDING thanks for your reply and happy new year! I do not fully understand what your means of he 11th of batch_instance.csv is a normalized value against its request,if it is normalized value against its request,why there are many values more than 1,or do i have misunderstand of normalized ?

Hi, I have checked the data, and found neither 'max_norm_mem' nor 'avg_norm_mem' larger than 1 according to my verification. Would you please show me the piece of data you found suspicious?

**Comment by HaiyangDING** [comment] 2018-01-07 03:08
> as the schema.csv said the usage is record every 1 minutes,and average over 300 seconds. were the fields linux cpu load average of 1 minute , linux cpu load average of 5 minute ,linux cpu load average of 15 minute in server_usage.csv computed in same way too?

linux cpu load average of 1/5/15min is a standard metric of CPU. You can have a look at its definition on related websites. I believe we sampled these data using standard method.

**Comment by CoffeeCandy** [comment] 2018-01-07 06:54
@HaiyangDING i am sorry,i used worng column of batch_instance.csv ,and i know 1/5/15 min is a standard metric of CPU.what i am confused is that these metric is record every minute,for example,
![image](https://user-images.githubusercontent.com/11613801/34647274-96083bbc-f3b9-11e7-9f24-c187ad15109e.png)this record,you record at 39480,39540,39600,39660,39720,so there are five record ,and as we know the cpu usage or memory usage is average of those five record,what i want to know is the 1/5/15 field you give is average too  or only record at 39600.

**Comment by HaiyangDING** [comment] 2018-01-10 13:45
Hi, @CoffeeCandy 

cpu load 1 / 5 / 15 are sampled with Tsar internally, please see Tsar [here](https://www.hi-linux.com/posts/5198.html)

As for the definition of cpu load 1 / 5 / 15, I think the computation is more complex than 'computing-the-average-of-some-records', you could refer to this [article](http://www.penglixun.com/tech/system/how_to_calc_load_cpu.html).

I hope this is helpful to you :)

**Comment by CoffeeCandy** [comment] 2018-01-11 04:40
@HaiyangDING thanks a lot~~

**Comment by Pia-Narmadha** [comment] 2018-03-01 20:57
I found that the 
start time of batch instance is in the range [0,61242] which is approx 17hrs
create time of batch task is in the range [5-60181] which is approx 16 hrs
timestamp of container event is in the range [34424, 79080] which is approx 12 hours.
timestamp of container usage in=s in the range [39600,82500] which is approx 11.9 hrs.

does all these time come inside the same time frame.

**Comment by HaiyangDING** [comment] 2018-03-02 06:23
@Pia-Narmadha 

They are in the same time frame, while the error of each time stamp number would be several seconds. 

The problem is that the first half of container event and usage is dropped. It is a unknown issue and sorry for the inconvenience. This will not happen in the second version of data.

**Comment by HaiyangDING** [comment] 2018-12-20 07:53
Closing the issue.

**Closed by HaiyangDING** 2018-12-20 07:53 UTC
Labels: question
