### ISSUE TITLE
Question about JobID and TaskID in batch_instance.csv

### ISSUE THREAD

**Issue by gaocegege** [alibaba/clusterdata#10] opened 2017-10-16 07:56 UTC
Hi, I found that 211305 records(1.31%) in batch_instance.csv has no JobID and TaskID.

There are some examples:

```
['65351', '65517', '', '', '269', 'Running', '1', '1', '', '', '', '']
['65351', '65517', '', '', '160', 'Running', '1', '1', '', '', '', '']
['65351', '65517', '', '', '224', 'Running', '1', '1', '', '', '', '']
['65351', '65517', '', '', '656', 'Running', '1', '1', '', '', '', '']
['65351', '65517', '', '', '1061', 'Running', '1', '1', '', '', '', '']
['65351', '65517', '', '', '416', 'Running', '1', '1', '', '', '', '']
['65351', '65517', '', '', '1014', 'Running', '1', '1', '', '', '', '']
['65351', '65517', '', '', '963', 'Running', '1', '1', '', '', '', '']
['65351', '65517', '', '', '1067', 'Running', '1', '1', '', '', '', '']
```
And their info about CPU and memory is missed, too. Is there any documentation about this kind of records?

I'd appreciate if you could help me :)

**Comment by HaiyangDING** [comment] 2017-12-29 02:41
Hi @gaocegege 

Again, this is another thing that should be added to "Know Issues". Thanks for pointing this out.

Please feel free to make the most use out of the current data set and we will publish another version of data in future.

**Comment by HaiyangDING** [comment] 2018-01-10 11:33
Closing the issue.

**Comment by HaiyangDING** [comment] 2018-03-08 09:52
@jcarreira 

Thanks for your valuable suggestions on this one and others, and I guess I need to run another thorough test on the data sooner.

I confirm the number is correct:

```
# len(instance_df[(instance_df['job_id'].isnull()) & (instance_df['task_id'].isnull())])
# 3992098
```

and they do take up to about 25% of the total entries. I think this is caused by a bug in data cleaning.

I think it is safe to count the resources used by these tasks as the numbers of the resource consumption are sampled by our monitors. Missing job_id and task_id causes trouble in characterizing the jobs though.

However, you could also do analysis by dropping these entries.

I cannot answer the question about how the paper "Imbalance ..." deals with these entries now and I would try to confirm with the author on this.

Again, sorry about inconvenience. We will definitely avoid all known mistakes in the second version of data.

**Comment by jcarreira** [comment] 2018-03-08 21:00
Thanks for the explanation. I have another comment about this.

I found that **all the tasks starting at around 70K seconds until the end (4-5hours) are missing the job_id/task_id**. Analysis down here [1]. This might indicate that there was an issue sometime during the trace.

**Can you please confirm this?** I think it would be important to clarify this to avoid misuses of the dataset.

[1] If we filter the entries in batch_instance.csv that have _start_timestamp_ in the range [60K, 89K[ and print the number of unique pairs <job_id,task_id> we see that most of the entries in this range are missing the task_id and job_id.

> grep -P "^[678]\d\d\d\d" batch_instance.csv | awk -F, '{print $3,$4}' | sort | uniq -c
3414302             **<< this is the number of entries without job_id and task_id**
   1999 11117 68093
      2 3814 22704
    724 572 3044

**Comment by HaiyangDING** [comment] 2018-03-12 03:38
Thanks for this worthy discovery @jcarreira 

I confirm that about 85% of the missing job_id^task_id are are of `start_timestamp` in the range between [60K, 89K[, and I think it is very helpful for us to avoid this in the second version.

Also, I will update the **Known Issue** part in the document so that more people could be aware of this.

Thank you again. We are really to have you be interested in our data. If you had any more suggestions to the next version of dataset, please let us know and we will try.

**Comment by HaiyangDING** [comment] 2018-12-20 07:52
Closing the issue.

**Closed by HaiyangDING** 2018-12-20 07:52 UTC
Labels: question
