### ISSUE TITLE
Max usage (CPU/mem) lower than average usage

### ISSUE THREAD

**Issue by jcarreira** [alibaba/clusterdata#30] opened 2018-03-04 02:58 UTC
I find records in batch_instance.csv for which the attributes for maximum utilization (_real_cpu_max_, _real_mem_max_) are lower than the attributes for average utilization (_real_cpu_avg_, _real_mem_avg_).

For instance, line 4475 of batch_instance.csv:

> 22556,22557,2632,15822,459,Terminated,1,1,**0.92,0.93**,0.002039706986255274,0.002153599254523335

Can you explain if this is normal and if not why this happens? I expect the values about maximum utilization to be equal or larger than the average.

**Comment by HaiyangDING** [comment] 2018-03-05 02:46
Hi, thanks for pointing this out. I think these are caused by a bug either the sampling or the cleaning procedure. 

I checked the data, these happen to a small portion of the entire dataset and we will try avoiding this in the next version of data. Sorry for the inconvenience here and very much thanks to your valuable suggestions / questions!

**Comment by HaiyangDING** [comment] 2018-12-20 07:48
Closing the issue.

**Closed by HaiyangDING** 2018-12-20 07:48 UTC
